import {
	DollarSign,
	GraduationCap,
	Loader2,
	Plus,
	Receipt,
	Search,
	User,
	Wallet,
} from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { PaymentDetailsModal } from "@/components/modals/PaymentDetailsModal";
import { StudentPaymentsBanner } from "@/components/payments/StudentPaymentsBanner";
import { TeacherPaymentsBanner } from "@/components/payments/TeacherPaymentsBanner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogFooter,
	DialogHeader,
	DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "@/components/ui/select";
import {
	Table,
	TableBody,
	TableCell,
	TableHead,
	TableHeader,
	TableRow,
} from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/contexts/AuthContext";
import { useDebouncedValue } from "@/hooks/useDebouncedValue";
import { fuzzyIncludes } from "@/lib/search";
import { trpc } from "@/lib/trpc";

interface PaymentHistoryItem {
	id: string;
	type: "student" | "teacher" | "expense";
	subType?: string;
	date: string;
	amount: string;
	status: string;
	person: { id: string; name: string } | null;
	class: { id: string; name: string } | null;
	course: { id: string; name: string } | null;
	sessionsCovered: number | null;
	invoiceNumber: string | null;
	autoGenerated: boolean;
	cycleNumber: number | null;
	paymentCycle?: string;
	notes: string | null;
	createdAt: string;
}

type PaymentType = "all" | "student" | "teacher" | "expense";
type StudentPaymentType = "all" | "tuition" | "books";

export function PaymentsPage() {
	const { user } = useAuth();
	const isAssistant = user?.role === "assistant";

	const [page, setPage] = useState(1);
	const [filterType, setFilterType] = useState<PaymentType>(
		isAssistant ? "student" : "all",
	);
	const [studentFilterType, setStudentFilterType] =
		useState<StudentPaymentType>("all");
	const [startDate, setStartDate] = useState<string>("");
	const [endDate, setEndDate] = useState<string>("");
	const [searchQuery, setSearchQuery] = useState("");
	const debouncedSearchQuery = useDebouncedValue(searchQuery, 350);
	const limit = 10;

	// Payment details modal state
	const [selectedPaymentDetails, setSelectedPaymentDetails] =
		useState<PaymentHistoryItem | null>(null);
	const [isDetailsModalOpen, setIsDetailsModalOpen] = useState(false);

	// Expense modal states
	const [isExpenseModalOpen, setIsExpenseModalOpen] = useState(false);
	const [expenseData, setExpenseData] = useState({
		category: "",
		amount: "",
		description: "",
		expenseDate: new Date().toISOString().split("T")[0],
	});

	const utils = trpc.useUtils();

	// Get date range for this month by default
	const today = new Date();
	const firstDayOfMonth = new Date(today.getFullYear(), today.getMonth(), 1);
	const lastDayOfMonth = new Date(today.getFullYear(), today.getMonth() + 1, 0);

	const effectiveStartDate = startDate ? new Date(startDate) : firstDayOfMonth;
	const effectiveEndDate = endDate ? new Date(endDate) : lastDayOfMonth;

	// Unified payment history query
	const { data: paymentHistory, isLoading: isLoadingHistory } =
		trpc.payments.getPaymentHistory.useQuery({
			page,
			limit,
			type: isAssistant ? "student" : filterType,
			startDate: effectiveStartDate,
			endDate: effectiveEndDate,
		});

	// Record expense mutation
	const recordExpenseMutation = trpc.payments.recordExpense.useMutation({
		onSuccess: () => {
			utils.payments.getPaymentHistory.invalidate();
			toast.success("تم تسجيل المصروفات بنجاح");
			setIsExpenseModalOpen(false);
			setExpenseData({
				category: "",
				amount: "",
				description: "",
				expenseDate: new Date().toISOString().split("T")[0],
			});
		},
		onError: (err) => {
			toast.error(err.message || "حدث خطأ أثناء تسجيل المصروفات");
		},
	});

	const handleRecordExpense = () => {
		if (!expenseData.category || !expenseData.amount) {
			toast.error("الرجاء إدخال التصنيف والمبلغ");
			return;
		}

		recordExpenseMutation.mutate({
			category: expenseData.category,
			amount: parseFloat(expenseData.amount),
			description: expenseData.description || undefined,
			expenseDate: new Date(expenseData.expenseDate),
		});
	};

	const resetFilters = () => {
		setFilterType(isAssistant ? "student" : "all");
		setStudentFilterType("all");
		setSearchQuery("");
		setStartDate("");
		setEndDate("");
		setPage(1);
	};

	// Filter payments based on search and student payment type
	const allPayments = paymentHistory?.data || [];
	const filteredPayments = allPayments.filter((payment) => {
		if (isAssistant && payment.type === "expense") {
			return false;
		}

		// Filter by search query
		if (debouncedSearchQuery) {
			const matches =
				fuzzyIncludes(payment.person?.name, debouncedSearchQuery) ||
				fuzzyIncludes(payment.class?.name, debouncedSearchQuery) ||
				fuzzyIncludes(payment.course?.name, debouncedSearchQuery);
			if (!matches) return false;
		}

		// Filter student payments by type
		if (payment.type === "student" && studentFilterType !== "all") {
			return payment.subType === studentFilterType;
		}

		if (filterType === "student" && payment.type !== "student") {
			return false;
		}

		return true;
	});

	const getPaymentTypeIcon = (type: string) => {
		switch (type) {
			case "student":
				return <User className="w-4 h-4" />;
			case "teacher":
				return <GraduationCap className="w-4 h-4" />;
			case "expense":
				return <Receipt className="w-4 h-4" />;
			default:
				return <DollarSign className="w-4 h-4" />;
		}
	};

	const getPaymentTypeLabel = (type: string, subType?: string) => {
		if (type === "student") {
			return subType === "books" ? "رسوم كتب" : "رسوم دراسية";
		}
		if (type === "teacher") return "راتب معلم";
		if (type === "expense") return "مصروفات";
		return type;
	};

	const totalPages = paymentHistory?.pagination?.totalPages || 1;

	return (
		<div className="space-y-6">
			{/* Header */}
			<div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
				<div>
					<h1 className="text-3xl font-bold text-text-heading">المدفوعات</h1>
					<p className="text-text-muted mt-1">
						إدارة دفعات الطلاب والمعلمين والمصروفات
					</p>
				</div>
				{!isAssistant ? (
					<Button onClick={() => setIsExpenseModalOpen(true)} className="gap-2">
						<Plus className="w-4 h-4" />
						تسجيل مصروفات
					</Button>
				) : (
					<div />
				)}
			</div>

			{/* Pending Payments Banners */}
			<div className="grid grid-cols-1 md:grid-cols-2 gap-6">
				<TeacherPaymentsBanner
					onRefresh={() => {
						utils.payments.getPaymentHistory.invalidate();
					}}
				/>
				<StudentPaymentsBanner
					onRefresh={() => {
						utils.payments.getPaymentHistory.invalidate();
					}}
				/>
			</div>

			{/* Filters */}
			<Card>
				<CardContent className="p-4">
					<div className="flex flex-col lg:flex-row gap-4">
						<div className="relative flex-1">
							<Search className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-text-muted" />
							<Input
								placeholder="البحث بالاسم، الكلاس..."
								value={searchQuery}
								onChange={(e) => setSearchQuery(e.target.value)}
								className="pr-10"
							/>
						</div>

						<div className="flex flex-col sm:flex-row gap-4">
							<Select
								value={filterType}
								onValueChange={(value) => {
									setFilterType(value as PaymentType);
									setPage(1);
								}}
								disabled={isAssistant}
							>
								<SelectTrigger className="w-[180px]">
									<SelectValue placeholder="نوع الدفعة" />
								</SelectTrigger>
								<SelectContent>
									<SelectItem value="all">الكل</SelectItem>
									<SelectItem value="student">دفعات الطلاب</SelectItem>
									{!isAssistant && (
										<>
											<SelectItem value="teacher">دفعات المعلمين</SelectItem>
											<SelectItem value="expense">المصروفات</SelectItem>
										</>
									)}
								</SelectContent>
							</Select>

							{(filterType === "student" || isAssistant) && (
								<Select
									value={studentFilterType}
									onValueChange={(value) => {
										setStudentFilterType(value as StudentPaymentType);
										setPage(1);
									}}
								>
									<SelectTrigger className="w-[150px]">
										<SelectValue placeholder="نوع الرسوم" />
									</SelectTrigger>
									<SelectContent>
										<SelectItem value="all">الكل</SelectItem>
										<SelectItem value="tuition">رسوم التسجيل</SelectItem>
										<SelectItem value="books">رسوم كتب</SelectItem>
									</SelectContent>
								</Select>
							)}

							<div className="flex gap-2">
								<Input
									type="date"
									value={startDate}
									onChange={(e) => {
										setStartDate(e.target.value);
										setPage(1);
									}}
									className="w-[140px]"
								/>
								<Input
									type="date"
									value={endDate}
									onChange={(e) => {
										setEndDate(e.target.value);
										setPage(1);
									}}
									className="w-[140px]"
								/>
							</div>

							<Button variant="outline" onClick={resetFilters}>
								إعادة ضبط
							</Button>
						</div>
					</div>
				</CardContent>
			</Card>

			{/* Payment History Table */}
			<Card>
				<CardHeader>
					<CardTitle className="flex items-center gap-2">
						<Wallet className="w-5 h-5" />
						سجل المدفوعات
					</CardTitle>
				</CardHeader>
				<CardContent className="p-0">
					{isLoadingHistory ? (
						<div className="flex items-center justify-center h-64">
							<Loader2 className="w-8 h-8 animate-spin text-primary" />
						</div>
					) : (
						<div className="overflow-x-auto">
							<Table>
								<TableHeader>
									<TableRow>
										<TableHead>التاريخ</TableHead>
										<TableHead>النوع</TableHead>
										<TableHead>المبلغ</TableHead>
										<TableHead>الشخص/التصنيف</TableHead>
										<TableHead>الكلاس</TableHead>
										<TableHead>التفاصيل</TableHead>
										<TableHead>الحالة</TableHead>
									</TableRow>
								</TableHeader>
								<TableBody>
									{filteredPayments.length === 0 ? (
										<TableRow>
											<TableCell
												colSpan={7}
												className="text-center py-8 text-text-muted"
											>
												لا توجد دفعات
											</TableCell>
										</TableRow>
									) : (
										filteredPayments.map((payment) => (
											<TableRow
												key={payment.id}
												className="cursor-pointer hover:bg-muted/50"
												onClick={() => {
													setSelectedPaymentDetails(payment);
													setIsDetailsModalOpen(true);
												}}
											>
												<TableCell>
													{new Date(payment.date).toLocaleDateString("ar-EG")}
												</TableCell>
												<TableCell>
													<Badge
														variant={
															payment.type === "student"
																? "default"
																: payment.type === "teacher"
																	? "secondary"
																	: "destructive"
														}
														className="gap-1"
													>
														{getPaymentTypeIcon(payment.type)}
														{getPaymentTypeLabel(payment.type, payment.subType)}
													</Badge>
												</TableCell>
												<TableCell className="font-medium">
													{payment.amount} جنيه
												</TableCell>
												<TableCell>
													{payment.person?.name || payment.subType || "-"}
												</TableCell>
												<TableCell>{payment.class?.name || "-"}</TableCell>
												<TableCell>
													<div className="flex flex-col gap-1">
														{payment.cycleNumber && (
															<span className="text-xs text-text-muted">
																دورة {payment.cycleNumber}
															</span>
														)}
														{payment.paymentCycle && (
															<span className="text-xs text-text-muted">
																{payment.paymentCycle} حصص
															</span>
														)}
														{payment.invoiceNumber && (
															<span className="text-xs text-text-muted">
																فاتورة: {payment.invoiceNumber}
															</span>
														)}
													</div>
												</TableCell>
												<TableCell>
													<Badge
														variant={
															payment.status === "paid" ? "success" : "warning"
														}
													>
														{payment.status === "paid" ? "تم السداد" : "معلق"}
													</Badge>
												</TableCell>
											</TableRow>
										))
									)}
								</TableBody>
							</Table>

							{/* Pagination */}
							{totalPages > 1 && (
								<div className="flex items-center justify-between px-4 py-4 border-t border-border-divider">
									<div className="text-sm text-text-muted">
										الصفحة {page} من {totalPages}
									</div>
									<div className="flex gap-2">
										<Button
											variant="outline"
											size="sm"
											onClick={() => setPage((p) => Math.max(1, p - 1))}
											disabled={page === 1}
										>
											السابق
										</Button>
										<Button
											variant="outline"
											size="sm"
											onClick={() =>
												setPage((p) => Math.min(totalPages, p + 1))
											}
											disabled={page === totalPages}
										>
											التالي
										</Button>
									</div>
								</div>
							)}
						</div>
					)}
				</CardContent>
			</Card>

			{/* Record Expense Dialog */}
			<Dialog
				open={isExpenseModalOpen && !isAssistant}
				onOpenChange={setIsExpenseModalOpen}
			>
				<DialogContent dir="rtl">
					<DialogHeader>
						<DialogTitle className="flex items-center gap-2">
							<Receipt className="w-5 h-5" />
							تسجيل مصروفات جديدة
						</DialogTitle>
						<DialogDescription>
							أدخل تفاصيل المصروفات ليتم تسجيلها في النظام
						</DialogDescription>
					</DialogHeader>

					<div className="space-y-4 py-4">
						<div className="space-y-2">
							<Label htmlFor="category">التصنيف *</Label>
							<Input
								id="category"
								value={expenseData.category}
								onChange={(e) =>
									setExpenseData({ ...expenseData, category: e.target.value })
								}
								placeholder="مثال: إيجار، كهرباء، ماء..."
							/>
						</div>

						<div className="space-y-2">
							<Label htmlFor="amount">المبلغ *</Label>
							<Input
								id="amount"
								type="number"
								value={expenseData.amount}
								onChange={(e) =>
									setExpenseData({ ...expenseData, amount: e.target.value })
								}
								placeholder="المبلغ بالجنيه"
							/>
						</div>

						<div className="space-y-2">
							<Label htmlFor="expenseDate">التاريخ</Label>
							<Input
								id="expenseDate"
								type="date"
								value={expenseData.expenseDate}
								onChange={(e) =>
									setExpenseData({
										...expenseData,
										expenseDate: e.target.value,
									})
								}
							/>
						</div>

						<div className="space-y-2">
							<Label htmlFor="description">الوصف</Label>
							<Textarea
								id="description"
								value={expenseData.description}
								onChange={(e) =>
									setExpenseData({
										...expenseData,
										description: e.target.value,
									})
								}
								placeholder="تفاصيل إضافية عن المصروف..."
							/>
						</div>
					</div>

					<DialogFooter className="gap-2">
						<Button
							variant="outline"
							onClick={() => setIsExpenseModalOpen(false)}
						>
							إلغاء
						</Button>
						<Button
							onClick={handleRecordExpense}
							disabled={recordExpenseMutation.isPending}
							className="gap-2"
						>
							{recordExpenseMutation.isPending && (
								<Loader2 className="w-4 h-4 animate-spin" />
							)}
							تسجيل المصروفات
						</Button>
					</DialogFooter>
				</DialogContent>
			</Dialog>

			{/* Payment Details Modal */}
			<PaymentDetailsModal
				payment={selectedPaymentDetails}
				isOpen={isDetailsModalOpen}
				onClose={() => setIsDetailsModalOpen(false)}
			/>
		</div>
	);
}
