import {
	AlertCircle,
	CheckSquare,
	GraduationCap,
	Loader2,
	User,
} from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogFooter,
	DialogHeader,
	DialogTitle,
} from "@/components/ui/dialog";
import {
	Table,
	TableBody,
	TableCell,
	TableHead,
	TableHeader,
	TableRow,
} from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";

interface PendingPayment {
	id: string;
	student?: { id: string; fullName: string } | null;
	teacher?: { id: string; fullName: string } | null;
	class?: { id: string; name: string } | null;
	course?: { id: string; name: string } | null;
	amount: string;
	type?: string;
	autoGenerated?: boolean;
	cycleNumber?: number;
	createdAt: Date;
	notes?: string;
}

export function PaymentsPage() {
	const [activeTab, setActiveTab] = useState("students");
	const [page, _setPage] = useState(1);
	const [selectedPayment, setSelectedPayment] = useState<PendingPayment | null>(
		null,
	);
	const [isSettleDialogOpen, setIsSettleDialogOpen] = useState(false);
	const [settleNotes, setSettleNotes] = useState("");
	const limit = 10;

	const utils = trpc.useUtils();

	// Fetch pending payments (always on top)
	const { data: pendingStudentPayments, isLoading: isLoadingPendingStudents } =
		trpc.payments.getPendingStudentPayments.useQuery();

	const { data: pendingTeacherPayments, isLoading: isLoadingPendingTeachers } =
		trpc.payments.getPendingTeacherPayments.useQuery(undefined, {
			enabled: activeTab === "teachers",
		});

	// Fetch regular payments
	const { data: studentPayments, isLoading: isLoadingStudentPayments } =
		trpc.payments.getStudentPayments.useQuery({
			page,
			limit,
		});

	const { data: teacherPayments, isLoading: isLoadingTeacherPayments } =
		trpc.payments.getTeacherPayments.useQuery(
			{
				page,
				limit,
			},
			{
				enabled: activeTab === "teachers",
			},
		);

	// Settle mutations
	const settleStudentMutation = trpc.payments.settleStudentPayment.useMutation({
		onSuccess: () => {
			utils.payments.getPendingStudentPayments.invalidate();
			utils.payments.getStudentPayments.invalidate();
			toast.success("تم تسديد الدفعة بنجاح");
			setIsSettleDialogOpen(false);
			setSelectedPayment(null);
			setSettleNotes("");
		},
		onError: (err) => {
			toast.error(err.message);
		},
	});

	const settleTeacherMutation = trpc.payments.settleTeacherPayment.useMutation({
		onSuccess: () => {
			utils.payments.getPendingTeacherPayments.invalidate();
			utils.payments.getTeacherPayments.invalidate();
			toast.success("تم تسديد دفعة المعلم بنجاح");
			setIsSettleDialogOpen(false);
			setSelectedPayment(null);
			setSettleNotes("");
		},
		onError: (err) => {
			toast.error(err.message);
		},
	});

	const handleSettleClick = (payment: PendingPayment) => {
		setSelectedPayment(payment);
		setIsSettleDialogOpen(true);
	};

	const confirmSettle = () => {
		if (!selectedPayment) return;

		if (activeTab === "students") {
			settleStudentMutation.mutate({
				paymentId: selectedPayment.id,
				notes: settleNotes,
			});
		} else {
			settleTeacherMutation.mutate({
				paymentId: selectedPayment.id,
				notes: settleNotes,
			});
		}
	};

	const studentPaymentsList = studentPayments?.data ?? [];
	const teacherPaymentsList = teacherPayments?.data ?? [];
	const pendingStudentList = pendingStudentPayments?.data ?? [];
	const pendingTeacherList = pendingTeacherPayments?.data ?? [];

	return (
		<div className="space-y-6">
			<div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
				<div>
					<h1 className="text-3xl font-bold text-text-heading">المدفوعات</h1>
					<p className="text-text-muted mt-1">إدارة دفعات الطلاب والمعلمين</p>
				</div>
			</div>

			<Tabs
				value={activeTab}
				onValueChange={setActiveTab}
				className="space-y-6"
			>
				<TabsList className="grid w-full max-w-md grid-cols-2">
					<TabsTrigger value="students" className="gap-2">
						<User className="w-4 h-4" />
						دفعات الطلاب
					</TabsTrigger>
					<TabsTrigger value="teachers" className="gap-2">
						<GraduationCap className="w-4 h-4" />
						دفعات المعلمين
					</TabsTrigger>
				</TabsList>

				<TabsContent value="students" className="space-y-6">
					{/* Pending Student Payments - Always on top */}
					{pendingStudentList.length > 0 && (
						<Card className="border-warning">
							<CardHeader>
								<CardTitle className="flex items-center gap-2 text-warning">
									<AlertCircle className="w-5 h-5" />
									دفعات معلقة ({pendingStudentList.length})
								</CardTitle>
							</CardHeader>
							<CardContent className="p-0">
								<div className="overflow-x-auto">
									<Table>
										<TableHeader>
											<TableRow>
												<TableHead>المبلغ</TableHead>
												<TableHead>الطالب</TableHead>
												<TableHead>الكلاس</TableHead>
												<TableHead>الدورة</TableHead>
												<TableHead className="text-left">الإجراءات</TableHead>
											</TableRow>
										</TableHeader>
										<TableBody>
											{pendingStudentList.map((payment) => (
												<TableRow key={payment.id} className="bg-warning/5">
													<TableCell>
														<span className="font-bold text-lg">
															{payment.amount} جنيه
														</span>
													</TableCell>
													<TableCell>{payment.student?.fullName}</TableCell>
													<TableCell>{payment.class?.name}</TableCell>
													<TableCell>
														<Badge variant="outline">
															دورة {payment.cycleNumber}
														</Badge>
													</TableCell>
													<TableCell className="text-left">
														<Button
															size="sm"
															onClick={() => handleSettleClick(payment)}
															className="gap-2"
														>
															<CheckSquare className="w-4 h-4" />
															تسديد
														</Button>
													</TableCell>
												</TableRow>
											))}
										</TableBody>
									</Table>
								</div>
							</CardContent>
						</Card>
					)}

					{/* Regular Student Payments */}
					<Card>
						<CardHeader>
							<CardTitle>سجل الدفعات</CardTitle>
						</CardHeader>
						<CardContent className="p-0">
							{isLoadingStudentPayments ? (
								<div className="flex items-center justify-center h-64">
									<Loader2 className="w-8 h-8 animate-spin text-primary" />
								</div>
							) : (
								<div className="overflow-x-auto">
									<Table>
										<TableHeader>
											<TableRow>
												<TableHead>الحالة</TableHead>
												<TableHead>التاريخ</TableHead>
												<TableHead>المبلغ</TableHead>
												<TableHead>نوع الدفعة</TableHead>
												<TableHead>الطالب</TableHead>
											</TableRow>
										</TableHeader>
										<TableBody>
											{studentPaymentsList.length === 0 ? (
												<TableRow>
													<TableCell
														colSpan={5}
														className="text-center py-8 text-text-muted"
													>
														لا توجد دفعات
													</TableCell>
												</TableRow>
											) : (
												studentPaymentsList.map((payment) => (
													<TableRow key={payment.id}>
														<TableCell>
															<Badge
																variant={
																	payment.status === "paid"
																		? "success"
																		: "warning"
																}
															>
																{payment.status === "paid"
																	? "تم السداد"
																	: "معلق"}
															</Badge>
														</TableCell>
														<TableCell>
															{new Date(payment.paymentDate).toLocaleDateString(
																"ar-EG",
															)}
														</TableCell>
														<TableCell className="font-medium">
															{payment.amount} جنيه
														</TableCell>
														<TableCell>
															{payment.type === "tuition"
																? "رسوم دراسية"
																: "كتب"}
														</TableCell>
														<TableCell>{payment.student?.fullName}</TableCell>
													</TableRow>
												))
											)}
										</TableBody>
									</Table>
								</div>
							)}
						</CardContent>
					</Card>
				</TabsContent>

				<TabsContent value="teachers" className="space-y-6">
					{/* Pending Teacher Payments - Always on top */}
					{pendingTeacherList.length > 0 && (
						<Card className="border-warning">
							<CardHeader>
								<CardTitle className="flex items-center gap-2 text-warning">
									<AlertCircle className="w-5 h-5" />
									دفعات معلقة ({pendingTeacherList.length})
								</CardTitle>
							</CardHeader>
							<CardContent className="p-0">
								<div className="overflow-x-auto">
									<Table>
										<TableHeader>
											<TableRow>
												<TableHead>المبلغ</TableHead>
												<TableHead>المعلم</TableHead>
												<TableHead>الكلاس</TableHead>
												<TableHead>الدورة</TableHead>
												<TableHead className="text-left">الإجراءات</TableHead>
											</TableRow>
										</TableHeader>
										<TableBody>
											{pendingTeacherList.map((payment) => (
												<TableRow key={payment.id} className="bg-warning/5">
													<TableCell>
														<span className="font-bold text-lg">
															{payment.amount} جنيه
														</span>
													</TableCell>
													<TableCell>{payment.teacher?.fullName}</TableCell>
													<TableCell>{payment.class?.name}</TableCell>
													<TableCell>
														<Badge variant="outline">
															دورة {payment.cycleNumber}
														</Badge>
													</TableCell>
													<TableCell className="text-left">
														<Button
															size="sm"
															onClick={() => handleSettleClick(payment)}
															className="gap-2"
														>
															<CheckSquare className="w-4 h-4" />
															تسديد
														</Button>
													</TableCell>
												</TableRow>
											))}
										</TableBody>
									</Table>
								</div>
							</CardContent>
						</Card>
					)}

					{/* Regular Teacher Payments */}
					<Card>
						<CardHeader>
							<CardTitle>سجل الدفعات</CardTitle>
						</CardHeader>
						<CardContent className="p-0">
							{isLoadingTeacherPayments ? (
								<div className="flex items-center justify-center h-64">
									<Loader2 className="w-8 h-8 animate-spin text-primary" />
								</div>
							) : (
								<div className="overflow-x-auto">
									<Table>
										<TableHeader>
											<TableRow>
												<TableHead>التاريخ</TableHead>
												<TableHead>المبلغ</TableHead>
												<TableHead>المعلم</TableHead>
												<TableHead>الكلاس</TableHead>
											</TableRow>
										</TableHeader>
										<TableBody>
											{teacherPaymentsList.length === 0 ? (
												<TableRow>
													<TableCell
														colSpan={4}
														className="text-center py-8 text-text-muted"
													>
														لا توجد دفعات
													</TableCell>
												</TableRow>
											) : (
												teacherPaymentsList.map((payment) => (
													<TableRow key={payment.id}>
														<TableCell>
															{new Date(payment.paymentDate).toLocaleDateString(
																"ar-EG",
															)}
														</TableCell>
														<TableCell className="font-medium">
															{payment.amount} جنيه
														</TableCell>
														<TableCell>{payment.teacher?.fullName}</TableCell>
														<TableCell>{payment.class?.name}</TableCell>
													</TableRow>
												))
											)}
										</TableBody>
									</Table>
								</div>
							)}
						</CardContent>
					</Card>
				</TabsContent>
			</Tabs>

			{/* Settle Confirmation Dialog */}
			<Dialog open={isSettleDialogOpen} onOpenChange={setIsSettleDialogOpen}>
				<DialogContent dir="rtl">
					<DialogHeader>
						<DialogTitle>تأكيد التسديد</DialogTitle>
						<DialogDescription>
							هل أنت متأكد من تسديد المبلغ التالي؟
						</DialogDescription>
					</DialogHeader>

					{selectedPayment && (
						<div className="space-y-4 py-4">
							<div className="bg-muted p-4 rounded-lg space-y-2">
								<div className="flex justify-between">
									<span className="text-muted-foreground">المبلغ:</span>
									<span className="font-bold text-lg">
										{selectedPayment.amount} جنيه
									</span>
								</div>
								<div className="flex justify-between">
									<span className="text-muted-foreground">
										{activeTab === "students" ? "الطالب:" : "المعلم:"}
									</span>
									<span className="font-medium">
										{activeTab === "students"
											? selectedPayment.student?.fullName
											: selectedPayment.teacher?.fullName}
									</span>
								</div>
								<div className="flex justify-between">
									<span className="text-muted-foreground">الكلاس:</span>
									<span>{selectedPayment.class?.name}</span>
								</div>
								{selectedPayment.cycleNumber && (
									<div className="flex justify-between">
										<span className="text-muted-foreground">الدورة:</span>
										<span>{selectedPayment.cycleNumber}</span>
									</div>
								)}
							</div>

							<div className="space-y-2">
								<label className="text-sm font-medium">ملاحظات (اختياري)</label>
								<Textarea
									value={settleNotes}
									onChange={(e) => setSettleNotes(e.target.value)}
									placeholder="أضف ملاحظات عن عملية التسديد..."
								/>
							</div>
						</div>
					)}

					<DialogFooter className="gap-2">
						<Button
							variant="outline"
							onClick={() => setIsSettleDialogOpen(false)}
						>
							إلغاء
						</Button>
						<Button
							onClick={confirmSettle}
							disabled={
								activeTab === "students"
									? settleStudentMutation.isPending
									: settleTeacherMutation.isPending
							}
							className="gap-2"
						>
							{(activeTab === "students"
								? settleStudentMutation.isPending
								: settleTeacherMutation.isPending) && (
								<Loader2 className="w-4 h-4 animate-spin" />
							)}
							تأكيد التسديد
						</Button>
					</DialogFooter>
				</DialogContent>
			</Dialog>
		</div>
	);
}
