import { BookOpen, Loader2, Search, Users, X } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import {
	Dialog,
	DialogContent,
	DialogHeader,
	DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "@/components/ui/select";
import { useDebouncedValue } from "@/hooks/useDebouncedValue";
import { fuzzyIncludes } from "@/lib/search";
import { trpc } from "@/lib/trpc";

interface StudentPaymentsBannerProps {
	onRefresh: () => void;
}

interface CourseGroupedPayment {
	course: { id: string; name: string } | null;
	count: number;
	paymentCount: number;
	studentCount: number;
	totalAmount: number;
	payments: Array<{
		id: string;
		student: { id: string; fullName: string } | null;
		class: { id: string; name: string } | null;
		type: string;
		amount: string;
		sessionsCovered: number | null;
		autoGenerated: boolean;
		cycleNumber: number | null;
		createdAt: string;
		notes: string | null;
	}>;
}

export function StudentPaymentsBanner({
	onRefresh,
}: StudentPaymentsBannerProps) {
	const utils = trpc.useUtils();
	const [isCoursesModalOpen, setIsCoursesModalOpen] = useState(false);
	const [selectedCourse, setSelectedCourse] = useState<{
		courseId: string;
		courseName: string;
		payments: CourseGroupedPayment["payments"];
	} | null>(null);
	const [searchQuery, setSearchQuery] = useState("");
	const [paymentTypeFilter, setPaymentTypeFilter] = useState<
		"all" | "tuition" | "books"
	>("all");
	const [confirmPaymentId, setConfirmPaymentId] = useState<string | null>(null);
	const debouncedSearchQuery = useDebouncedValue(searchQuery, 300);

	const { data, isLoading } = trpc.payments.getPendingPaymentsByCourse.useQuery(
		undefined,
		{
			enabled: true,
		},
	);

	const settleMutation = trpc.payments.settleStudentPayment.useMutation({
		onSuccess: () => {
			toast.success("تم تسديد الدفعة بنجاح");
			utils.payments.getPendingPaymentsByCourse.invalidate();
			utils.payments.getPendingStudentPayments.invalidate();
			onRefresh();
		},
		onError: (err) => {
			toast.error(err.message);
		},
	});

	const courses: CourseGroupedPayment[] = data?.data || [];
	const totalCourses = courses.length;
	const totalPendingAmount = courses.reduce((sum, c) => sum + c.totalAmount, 0);
	const totalStudents = courses.reduce((sum, c) => sum + c.studentCount, 0);

	const handleCourseClick = (course: CourseGroupedPayment) => {
		if (!course.course) return;
		setSelectedCourse({
			courseId: course.course.id,
			courseName: course.course.name,
			payments: course.payments,
		});
		setSearchQuery("");
	};

	const handleSettle = (paymentId: string) => {
		settleMutation.mutate({
			paymentId,
			notes: `تسديد فردي من صفحة الدفعات`,
		});
	};

	// Filter payments by search query
	const filteredPayments = selectedCourse?.payments.filter((payment) => {
		const searchMatches =
			!debouncedSearchQuery ||
			fuzzyIncludes(payment.student?.fullName, debouncedSearchQuery) ||
			fuzzyIncludes(payment.class?.name, debouncedSearchQuery);

		const typeMatches =
			paymentTypeFilter === "all" || payment.type === paymentTypeFilter;

		return searchMatches && typeMatches;
	});

	return (
		<>
			{/* Banner */}
			<Card
				className="cursor-pointer hover:bg-muted/50 transition-colors border-l-4 border-l-success"
				onClick={() => setIsCoursesModalOpen(true)}
				onKeyDown={(e) => {
					if (e.key === "Enter" || e.key === " ") {
						e.preventDefault();
						setIsCoursesModalOpen(true);
					}
				}}
				role="button"
				tabIndex={0}
			>
				<CardContent className="p-4">
					<div className="flex items-center justify-between">
						<div className="flex items-center gap-4">
							<div className="w-12 h-12 rounded-full bg-success/10 flex items-center justify-center">
								<BookOpen className="w-6 h-6 text-success" />
							</div>
							<div>
								<h3 className="font-bold text-lg">دفعات الطلاب</h3>
								<p className="text-sm text-muted-foreground">
									{totalStudents} طالب لديهم دفعات معلقة في {totalCourses} كورس
								</p>
							</div>
						</div>
						<div className="text-left">
							<p className="text-2xl font-bold text-success">
								{totalPendingAmount.toFixed(2)} جنيه
							</p>
							<p className="text-sm text-muted-foreground">إجمالي المعلق</p>
						</div>
					</div>
				</CardContent>
			</Card>

			{/* Courses List Modal */}
			<Dialog open={isCoursesModalOpen} onOpenChange={setIsCoursesModalOpen}>
				<DialogContent className="max-w-3xl" dir="rtl">
					<DialogHeader>
						<DialogTitle className="flex items-center gap-2 text-xl">
							<BookOpen className="w-6 h-6" />
							الكورسات ذات الدفعات المعلقة
						</DialogTitle>
					</DialogHeader>

					{isLoading ? (
						<div className="flex items-center justify-center h-32">
							<Loader2 className="w-8 h-8 animate-spin" />
						</div>
					) : courses.length === 0 ? (
						<div className="text-center py-8 text-muted-foreground">
							لا يوجد كورسات لديها دفعات معلقة
						</div>
					) : (
						<div className="grid gap-3 md:grid-cols-2 max-h-[60vh] overflow-y-auto">
							{courses.map((course) =>
								course.course ? (
									<button
										key={course.course.id}
										type="button"
										className="flex items-center justify-between p-4 border rounded-xl hover:bg-muted/40 cursor-pointer transition-colors"
										onClick={() => handleCourseClick(course)}
										onKeyDown={(e) => {
											if (e.key === "Enter" || e.key === " ") {
												e.preventDefault();
												handleCourseClick(course);
											}
										}}
										aria-label={`عرض دفعات كورس ${course.course.name}`}
									>
										<div className="flex items-center gap-3">
											<div className="w-10 h-10 rounded-full bg-success/10 flex items-center justify-center">
												<Users className="w-5 h-5 text-success" />
											</div>
											<div>
												<p className="font-medium">{course.course.name}</p>
												<p className="text-sm text-muted-foreground">
													{course.studentCount} طالب - {course.paymentCount}{" "}
													دفعة
												</p>
											</div>
										</div>
										<div className="text-left">
											<p className="text-xl font-bold text-success">
												{course.totalAmount.toFixed(2)} جنيه
											</p>
										</div>
									</button>
								) : null,
							)}
						</div>
					)}
				</DialogContent>
			</Dialog>

			{/* Course Students Payments Modal */}
			<Dialog
				open={!!selectedCourse}
				onOpenChange={() => setSelectedCourse(null)}
			>
				<DialogContent className="max-w-4xl" dir="rtl">
					<DialogHeader>
						<DialogTitle className="flex items-center justify-between">
							<span>دفعات طلاب {selectedCourse?.courseName}</span>
							<Button
								variant="ghost"
								size="icon"
								onClick={() => setSelectedCourse(null)}
							>
								<X className="w-4 h-4" />
							</Button>
						</DialogTitle>
					</DialogHeader>

					{selectedCourse && (
						<div className="space-y-4">
							{/* Search */}
							<div className="grid md:grid-cols-2 gap-3">
								<div className="relative">
									<Search className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
									<Input
										placeholder="البحث باسم الطالب أو الكلاس..."
										value={searchQuery}
										onChange={(e) => setSearchQuery(e.target.value)}
										className="pr-10"
									/>
								</div>
								<Select
									value={paymentTypeFilter}
									onValueChange={(value: "all" | "tuition" | "books") =>
										setPaymentTypeFilter(value)
									}
								>
									<SelectTrigger>
										<SelectValue placeholder="نوع الدفعة" />
									</SelectTrigger>
									<SelectContent>
										<SelectItem value="all">الكل</SelectItem>
										<SelectItem value="tuition">رسوم التسجيل</SelectItem>
										<SelectItem value="books">رسوم الكتب</SelectItem>
									</SelectContent>
								</Select>
							</div>

							{/* Payments List */}
							<div className="space-y-2 max-h-[50vh] overflow-y-auto">
								{filteredPayments?.length === 0 ? (
									<div className="text-center py-8 text-muted-foreground">
										لا توجد دفعات مطابقة للبحث
									</div>
								) : (
									filteredPayments?.map((payment, index: number) => (
										<div
											key={payment.id}
											className="flex items-center justify-between p-3 bg-muted/50 rounded-lg"
										>
											<div className="flex items-center gap-3">
												<span className="text-sm text-muted-foreground w-6">
													{index + 1}
												</span>
												<div>
													<p className="font-medium">
														{payment.student?.fullName}
													</p>
													<div className="flex items-center gap-2 text-sm text-muted-foreground">
														<span>{payment.class?.name}</span>
														{payment.type === "books" && (
															<Badge variant="secondary" className="text-xs">
																كتب
															</Badge>
														)}
														{payment.type === "tuition" && (
															<Badge variant="outline" className="text-xs">
																رسوم دراسية
															</Badge>
														)}
													</div>
												</div>
											</div>
											<div className="flex items-center gap-4">
												<div className="text-left">
													<p className="font-bold">{payment.amount} جنيه</p>
													{payment.cycleNumber && (
														<p className="text-xs text-muted-foreground">
															دورة {payment.cycleNumber}
														</p>
													)}
												</div>
												<Button
													size="sm"
													onClick={() => setConfirmPaymentId(payment.id)}
													disabled={settleMutation.isPending}
												>
													{settleMutation.isPending ? (
														<Loader2 className="w-4 h-4 animate-spin" />
													) : (
														"تسديد"
													)}
												</Button>
											</div>
										</div>
									))
								)}
							</div>

							<div className="border-t pt-4">
								<div className="flex items-center justify-between">
									<p className="text-sm text-muted-foreground">
										إجمالي: {filteredPayments?.length || 0} دفعة
									</p>
									<p className="text-xl font-bold text-success">
										{filteredPayments
											?.reduce(
												(sum: number, p) => sum + parseFloat(p.amount),
												0,
											)
											.toFixed(2)}{" "}
										جنيه
									</p>
								</div>
							</div>
						</div>
					)}
				</DialogContent>
			</Dialog>

			<Dialog
				open={!!confirmPaymentId}
				onOpenChange={() => setConfirmPaymentId(null)}
			>
				<DialogContent dir="rtl">
					<DialogHeader>
						<DialogTitle>تأكيد التسوية</DialogTitle>
					</DialogHeader>
					<p className="text-sm text-text-muted">
						هل تريد تسوية هذه الدفعة الآن؟
					</p>
					<div className="flex items-center justify-end gap-2 mt-4">
						<Button variant="outline" onClick={() => setConfirmPaymentId(null)}>
							إلغاء
						</Button>
						<Button
							onClick={() => {
								if (confirmPaymentId) {
									handleSettle(confirmPaymentId);
								}
								setConfirmPaymentId(null);
							}}
							disabled={settleMutation.isPending}
						>
							تأكيد
						</Button>
					</div>
				</DialogContent>
			</Dialog>
		</>
	);
}
