import { GraduationCap, Loader2, Search, Users, Wallet, X } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import {
	Dialog,
	DialogContent,
	DialogHeader,
	DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { useDebouncedValue } from "@/hooks/useDebouncedValue";
import { fuzzyIncludes } from "@/lib/search";
import { trpc } from "@/lib/trpc";

interface TeacherPaymentsBannerProps {
	onRefresh: () => void;
}

interface TeacherGroupedPayment {
	teacher: { id: string; name: string } | null;
	count: number;
	paymentCount: number;
	totalAmount: number;
	payments: Array<{
		id: string;
		amount: string;
		class: { id: string; name: string } | null;
		course?: { id: string; name: string } | null;
		level?: { id: string; levelNumber: number } | null;
		sessionsCovered: number | null;
		autoGenerated: boolean;
		cycleNumber: number | null;
		paymentCycle: string;
		createdAt: string;
		notes: string | null;
	}>;
}

export function TeacherPaymentsBanner({
	onRefresh,
}: TeacherPaymentsBannerProps) {
	const utils = trpc.useUtils();
	const [isTeachersModalOpen, setIsTeachersModalOpen] = useState(false);
	const [selectedTeacher, setSelectedTeacher] = useState<{
		teacherId: string;
		teacherName: string;
		payments: TeacherGroupedPayment["payments"];
		totalAmount: number;
	} | null>(null);
	const [searchQuery, setSearchQuery] = useState("");
	const [confirmSinglePaymentId, setConfirmSinglePaymentId] = useState<
		string | null
	>(null);
	const [confirmBulk, setConfirmBulk] = useState(false);

	const debouncedSearchQuery = useDebouncedValue(searchQuery, 300);

	const { data, isLoading } =
		trpc.payments.getPendingPaymentsByTeacher.useQuery(undefined, {
			enabled: true,
			retry: 0,
		});

	const bulkSettleMutation =
		trpc.payments.bulkSettleTeacherPayments.useMutation({
			onSuccess: (result) => {
				toast.success(
					`تم تسديد ${result.settledCount} دفعات بمبلغ ${result.totalAmount} جنيه`,
				);
				utils.payments.getPendingPaymentsByTeacher.invalidate();
				utils.payments.getPendingTeacherPayments.invalidate();
				setSelectedTeacher(null);
				onRefresh();
			},
			onError: (err) => {
				toast.error(err.message);
			},
		});

	const settleSingleMutation = trpc.payments.settleTeacherPayment.useMutation({
		onSuccess: () => {
			toast.success("تم تسوية الدفعة بنجاح");
			utils.payments.getPendingPaymentsByTeacher.invalidate();
			utils.payments.getPendingTeacherPayments.invalidate();
			onRefresh();
		},
		onError: (err) => {
			toast.error(err.message);
		},
	});

	const teachers: TeacherGroupedPayment[] = data?.data || [];
	const totalTeachers = teachers.length;
	const totalPendingAmount = teachers.reduce(
		(sum, teacher) => sum + teacher.totalAmount,
		0,
	);

	const handleTeacherClick = (teacher: TeacherGroupedPayment) => {
		if (!teacher.teacher) return;

		setSelectedTeacher({
			teacherId: teacher.teacher.id,
			teacherName: teacher.teacher.name,
			payments: teacher.payments,
			totalAmount: teacher.totalAmount,
		});
		setSearchQuery("");
	};

	const filteredTeacherPayments = selectedTeacher?.payments.filter(
		(payment) => {
			if (!debouncedSearchQuery) return true;
			return fuzzyIncludes(payment.class?.name, debouncedSearchQuery);
		},
	);

	const handleBulkSettle = () => {
		if (!selectedTeacher) return;

		bulkSettleMutation.mutate({
			teacherId: selectedTeacher.teacherId,
			notes: `تسديد جميع الدفعات المعلقة - ${selectedTeacher.teacherName}`,
		});
	};

	const filteredPaymentsTotal = filteredTeacherPayments?.reduce(
		(sum, payment) => sum + parseFloat(payment.amount),
		0,
	);

	return (
		<>
			<Card
				className="cursor-pointer hover:bg-muted/50 transition-colors border-l-4 border-l-primary"
				onClick={() => setIsTeachersModalOpen(true)}
				onKeyDown={(e) => {
					if (e.key === "Enter" || e.key === " ") {
						e.preventDefault();
						setIsTeachersModalOpen(true);
					}
				}}
				role="button"
				tabIndex={0}
			>
				<CardContent className="p-4">
					<div className="flex items-center justify-between">
						<div className="flex items-center gap-4">
							<div className="w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center">
								<GraduationCap className="w-6 h-6 text-primary" />
							</div>
							<div>
								<h3 className="font-bold text-lg">دفعات المعلمين</h3>
								<p className="text-sm text-muted-foreground">
									{totalTeachers} معلم لديهم دفعات معلقة
								</p>
							</div>
						</div>
						<div className="text-left">
							<p className="text-2xl font-bold text-primary">
								{totalPendingAmount.toFixed(2)} جنيه
							</p>
							<p className="text-sm text-muted-foreground">إجمالي المعلق</p>
						</div>
					</div>
				</CardContent>
			</Card>

			<Dialog open={isTeachersModalOpen} onOpenChange={setIsTeachersModalOpen}>
				<DialogContent className="max-w-3xl" dir="rtl">
					<DialogHeader>
						<DialogTitle className="flex items-center gap-2 text-xl">
							<GraduationCap className="w-6 h-6" />
							المعلمون ذوو الدفعات المعلقة
						</DialogTitle>
					</DialogHeader>

					{isLoading ? (
						<div className="flex items-center justify-center h-32">
							<Loader2 className="w-8 h-8 animate-spin" />
						</div>
					) : teachers.length === 0 ? (
						<div className="text-center py-8 text-muted-foreground">
							لا يوجد معلمون لديهم دفعات معلقة
						</div>
					) : (
						<div className="grid md:grid-cols-2 gap-3 max-h-[60vh] overflow-y-auto">
							{teachers.map((teacher) =>
								teacher.teacher ? (
									<button
										key={teacher.teacher.id}
										type="button"
										className="flex items-center justify-between p-4 border rounded-xl hover:bg-muted/40 cursor-pointer transition-colors"
										onClick={() => handleTeacherClick(teacher)}
										aria-label={`عرض دفعات ${teacher.teacher.name}`}
									>
										<div className="flex items-center gap-3">
											<div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center">
												<Users className="w-5 h-5 text-primary" />
											</div>
											<div>
												<p className="font-medium">{teacher.teacher.name}</p>
												<p className="text-sm text-muted-foreground">
													{teacher.paymentCount} دفعة معلقة
												</p>
											</div>
										</div>
										<div className="text-left">
											<p className="text-xl font-bold text-primary">
												{teacher.totalAmount.toFixed(2)} جنيه
											</p>
										</div>
									</button>
								) : null,
							)}
						</div>
					)}
				</DialogContent>
			</Dialog>

			<Dialog
				open={!!selectedTeacher}
				onOpenChange={() => setSelectedTeacher(null)}
			>
				<DialogContent className="max-w-4xl" dir="rtl">
					<DialogHeader>
						<DialogTitle className="flex items-center justify-between">
							<span className="flex items-center gap-2">
								<Wallet className="w-6 h-6" />
								دفعات {selectedTeacher?.teacherName}
							</span>
							<Button
								variant="ghost"
								size="icon"
								onClick={() => setSelectedTeacher(null)}
							>
								<X className="w-4 h-4" />
							</Button>
						</DialogTitle>
					</DialogHeader>

					{selectedTeacher && (
						<div className="space-y-4">
							<div className="relative">
								<Search className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
								<Input
									placeholder="البحث بالكلاس..."
									value={searchQuery}
									onChange={(e) => setSearchQuery(e.target.value)}
									className="pr-10"
								/>
							</div>

							<div className="space-y-2 max-h-[50vh] overflow-y-auto">
								{filteredTeacherPayments?.map((payment, index) => (
									<div
										key={payment.id}
										className="flex items-center justify-between p-3 bg-muted/50 rounded-lg"
									>
										<div className="flex items-center gap-3">
											<span className="text-sm text-muted-foreground w-6">
												{index + 1}
											</span>
											<div>
												<p className="font-medium">{payment.class?.name}</p>
												<p className="text-sm text-muted-foreground">
													{payment.course?.name || "-"} - مستوى{" "}
													{payment.level?.levelNumber || "-"}
												</p>
												<p className="text-sm text-muted-foreground">
													دورة {payment.cycleNumber}
													{payment.paymentCycle &&
														` (${payment.paymentCycle} حصص)`}
												</p>
												<p className="text-xs text-muted-foreground">
													الشهر:{" "}
													{new Date(payment.createdAt).toLocaleDateString(
														"ar-EG",
														{ month: "long", year: "numeric" },
													)}
												</p>
											</div>
										</div>
										<div className="flex items-center gap-4">
											<p className="font-bold">{payment.amount} جنيه</p>
											<Badge variant="warning">معلق</Badge>
											<Button
												size="sm"
												onClick={() => setConfirmSinglePaymentId(payment.id)}
												disabled={settleSingleMutation.isPending}
											>
												تسديد
											</Button>
										</div>
									</div>
								))}
							</div>

							<div className="border-t pt-4">
								<div className="flex items-center justify-between">
									<div>
										<p className="text-sm text-muted-foreground">
											إجمالي الدفعات:
										</p>
										<p className="text-3xl font-bold text-primary">
											{(
												filteredPaymentsTotal ?? selectedTeacher.totalAmount
											).toFixed(2)}{" "}
											جنيه
										</p>
									</div>
									<Button
										onClick={() => setConfirmBulk(true)}
										disabled={bulkSettleMutation.isPending}
										className="gap-2"
									>
										{bulkSettleMutation.isPending && (
											<Loader2 className="w-4 h-4 animate-spin" />
										)}
										تسديد الكل
									</Button>
								</div>
							</div>
						</div>
					)}
				</DialogContent>
			</Dialog>

			<Dialog
				open={!!confirmSinglePaymentId}
				onOpenChange={() => setConfirmSinglePaymentId(null)}
			>
				<DialogContent dir="rtl">
					<DialogHeader>
						<DialogTitle>تأكيد التسوية</DialogTitle>
					</DialogHeader>
					<p className="text-sm text-muted-foreground">
						هل تريد تسديد هذه الدفعة؟
					</p>
					<div className="flex items-center justify-end gap-2 mt-3">
						<Button
							variant="outline"
							onClick={() => setConfirmSinglePaymentId(null)}
						>
							إلغاء
						</Button>
						<Button
							onClick={() => {
								if (confirmSinglePaymentId) {
									settleSingleMutation.mutate({
										paymentId: confirmSinglePaymentId,
									});
								}
								setConfirmSinglePaymentId(null);
							}}
						>
							تأكيد
						</Button>
					</div>
				</DialogContent>
			</Dialog>

			<Dialog open={confirmBulk} onOpenChange={setConfirmBulk}>
				<DialogContent dir="rtl">
					<DialogHeader>
						<DialogTitle>تأكيد التسوية الجماعية</DialogTitle>
					</DialogHeader>
					<p className="text-sm text-muted-foreground">
						هل تريد تسديد جميع دفعات هذا المعلم؟
					</p>
					<div className="flex items-center justify-end gap-2 mt-3">
						<Button variant="outline" onClick={() => setConfirmBulk(false)}>
							إلغاء
						</Button>
						<Button
							onClick={() => {
								handleBulkSettle();
								setConfirmBulk(false);
							}}
						>
							تأكيد
						</Button>
					</div>
				</DialogContent>
			</Dialog>
		</>
	);
}
