import { format } from "date-fns";
import { ar } from "date-fns/locale";
import { Badge } from "@/components/ui/badge";
import {
	Dialog,
	DialogContent,
	DialogHeader,
	DialogTitle,
} from "@/components/ui/dialog";

interface PaymentDetailsModalProps {
	isOpen: boolean;
	onClose: () => void;
	payment: {
		id: string;
		type: string;
		subType?: string;
		date: string;
		amount: string;
		status: string;
		person?: { id: string; name: string } | null;
		class?: { id: string; name: string } | null;
		course?: { id: string; name: string } | null;
		sessionsCovered?: number | null;
		invoiceNumber?: string | null;
		autoGenerated?: boolean;
		cycleNumber?: number | null;
		paymentCycle?: string | null;
		notes?: string | null;
		createdAt: string;
	} | null;
}

export function PaymentDetailsModal({
	isOpen,
	onClose,
	payment,
}: PaymentDetailsModalProps) {
	if (!payment) return null;

	const getPaymentTypeLabel = () => {
		if (payment.type === "student") {
			return payment.subType === "books" ? "رسوم كتب" : "رسوم دراسية";
		}
		if (payment.type === "teacher") return "راتب معلم";
		if (payment.type === "expense") return "مصروفات";
		return payment.type;
	};

	const getStatusBadge = () => {
		if (payment.type === "expense") {
			return <Badge variant="default">تم التسجيل</Badge>;
		}
		return payment.status === "paid" ? (
			<Badge variant="success">تم السداد</Badge>
		) : (
			<Badge variant="warning">معلق</Badge>
		);
	};

	return (
		<Dialog open={isOpen} onOpenChange={onClose}>
			<DialogContent className="max-w-md" dir="rtl">
				<DialogHeader>
					<DialogTitle className="text-right">تفاصيل الدفعة</DialogTitle>
				</DialogHeader>

				<div className="space-y-4">
					{/* Type and Status */}
					<div className="flex items-center justify-between">
						<span className="text-muted-foreground">نوع الدفعة:</span>
						<Badge variant="outline">{getPaymentTypeLabel()}</Badge>
					</div>
					<div className="flex items-center justify-between">
						<span className="text-muted-foreground">الحالة:</span>
						{getStatusBadge()}
					</div>

					<div className="border-t my-4" />

					{/* Amount */}
					<div className="flex items-center justify-between">
						<span className="text-muted-foreground">المبلغ:</span>
						<span className="text-xl font-bold">{payment.amount} جنيه</span>
					</div>

					{/* Person */}
					{payment.person && (
						<div className="flex items-center justify-between">
							<span className="text-muted-foreground">
								{payment.type === "teacher" ? "المعلم:" : "الطالب:"}
							</span>
							<span className="font-medium">{payment.person.name}</span>
						</div>
					)}

					{/* Class */}
					{payment.class && (
						<div className="flex items-center justify-between">
							<span className="text-muted-foreground">الكلاس:</span>
							<span className="font-medium">{payment.class.name}</span>
						</div>
					)}

					{/* Course */}
					{payment.course && (
						<div className="flex items-center justify-between">
							<span className="text-muted-foreground">الكورس:</span>
							<span className="font-medium">{payment.course.name}</span>
						</div>
					)}

					{/* Sessions */}
					{payment.sessionsCovered && (
						<div className="flex items-center justify-between">
							<span className="text-muted-foreground">الحصص المشمولة:</span>
							<span className="font-medium">{payment.sessionsCovered} حصة</span>
						</div>
					)}

					{/* Cycle */}
					{payment.cycleNumber && (
						<div className="flex items-center justify-between">
							<span className="text-muted-foreground">الدورة:</span>
							<span className="font-medium">{payment.cycleNumber}</span>
						</div>
					)}

					{/* Payment Cycle (for teachers) */}
					{payment.paymentCycle && (
						<div className="flex items-center justify-between">
							<span className="text-muted-foreground">دورة الدفع:</span>
							<span className="font-medium">كل {payment.paymentCycle} حصص</span>
						</div>
					)}

					{/* Invoice Number */}
					{payment.invoiceNumber && (
						<div className="flex items-center justify-between">
							<span className="text-muted-foreground">رقم الفاتورة:</span>
							<span className="font-medium">{payment.invoiceNumber}</span>
						</div>
					)}

					{/* Auto Generated */}
					{payment.autoGenerated && (
						<div className="flex items-center justify-between">
							<span className="text-muted-foreground">التوليد:</span>
							<Badge variant="secondary">تلقائي</Badge>
						</div>
					)}

					<div className="border-t my-4" />

					{/* Dates */}
					<div className="flex items-center justify-between">
						<span className="text-muted-foreground">تاريخ الدفعة:</span>
						<span className="font-medium">
							{format(new Date(payment.date), "dd MMMM yyyy", { locale: ar })}
						</span>
					</div>
					<div className="flex items-center justify-between">
						<span className="text-muted-foreground">تاريخ الإنشاء:</span>
						<span className="font-medium">
							{format(new Date(payment.createdAt), "dd MMMM yyyy - HH:mm", {
								locale: ar,
							})}
						</span>
					</div>

					{/* Notes */}
					{payment.notes && (
						<>
							<div className="border-t my-4" />
							<div className="space-y-2">
								<span className="text-muted-foreground">ملاحظات:</span>
								<p className="text-sm bg-muted p-3 rounded-md whitespace-pre-wrap">
									{payment.notes}
								</p>
							</div>
						</>
					)}
				</div>
			</DialogContent>
		</Dialog>
	);
}
